# Generated by Django 4.2.6 on 2023-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM_Website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record", name="zipcode", field=models.CharField(max_length=10),
        ),
    ]
